FROM python:3.11-slim

WORKDIR /srv

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libc6-dev \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY mabd/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY mabd ./mabd

WORKDIR /srv/mabd

EXPOSE 8002

CMD ["python", "manage.py", "runserver", "0.0.0.0:8002"]
